#!/usr/bin/env node
import path from 'node:path';import {root,cdir,argMap,readJson,StateStore,EngineeringOSError,failClosed} from './lib/core.mjs';
const a=argMap(),cmd=a._[0]||'validate',r=root(),store=new StateStore(r),registry=readJson(path.join(cdir(r),'agents','registry.json'),{}),roles=new Map((registry.agents||[]).map(x=>[x.name,x]));
try{
let g=cmd==='save'?JSON.parse(String(a.json||'null')):store.read().executionGraph;if(!g)throw new EngineeringOSError('POLICY_BLOCKED','execution graph missing');
const errs=[];const ids=new Set();if(!Array.isArray(g.nodes)||g.nodes.length===0)errs.push('nodes-empty');for(const n of g.nodes||[]){if(ids.has(n.id))errs.push(`duplicate-node:${n.id}`);ids.add(n.id);const role=roles.get(n.role);if(!role)errs.push(`unknown-role:${n.id}:${n.role}`);else if(role.mode!==n.mode)errs.push(`mode-mismatch:${n.id}:${n.mode}:${role.mode}`);if(n.mode==='write'&&(!Array.isArray(n.ownership)||n.ownership.length===0))errs.push(`writer-without-ownership:${n.id}`);if(!Number.isInteger(n.retryBudget)||n.retryBudget<0)errs.push(`invalid-retry-budget:${n.id}`);if(!Number.isInteger(n.timeoutMs)||n.timeoutMs<1)errs.push(`invalid-timeout:${n.id}`);if(!n.executionId||!store.read().executions.some(x=>x.executionId===n.executionId))errs.push(`invalid-execution-binding:${n.id}`)}for(const n of g.nodes||[])for(const d of n.dependsOn||[])if(!ids.has(d))errs.push(`missing-dependency:${n.id}->${d}`);
const temp=new Set(),done=new Set(),byId=new Map((g?.nodes||[]).map(n=>[n.id,n]));function dfs(id){if(temp.has(id)){errs.push(`cycle:${id}`);return}if(done.has(id))return;temp.add(id);for(const d of byId.get(id)?.dependsOn||[])dfs(d);temp.delete(id);done.add(id)}for(const id of ids)dfs(id);
const ancestors=id=>{const out=new Set();const visit=x=>{for(const d of byId.get(x)?.dependsOn||[])if(!out.has(d)){out.add(d);visit(d)}};visit(id);return out};const norm=x=>String(x).replace(/\\/g,'/').replace(/\/\*\*?$/,'').replace(/\/$/,'');const overlaps=(a,b)=>{a=norm(a);b=norm(b);return a===b||a.startsWith(b+'/')||b.startsWith(a+'/')};const writers=(g?.nodes||[]).filter(n=>n.mode==='write');for(let i=0;i<writers.length;i++)for(let j=i+1;j<writers.length;j++){const ai=ancestors(writers[i].id),aj=ancestors(writers[j].id);if(ai.has(writers[j].id)||aj.has(writers[i].id))continue;for(const p of writers[i].ownership||[])for(const q of writers[j].ownership||[])if(overlaps(p,q))errs.push(`parallel-writer-overlap:${writers[i].id}:${writers[j].id}:${p}:${q}`)}
if(cmd==='save'&&!errs.length)store.transaction(state=>{state.executionGraph={...g,status:'VALIDATED',validatedAt:new Date().toISOString()}});
const out={verdict:errs.length?'BLOCKED':'PASS',nodes:g?.nodes?.length||0,errors:[...new Set(errs)]};console.log(JSON.stringify(out,null,2));process.exit(errs.length?2:0);
}catch(error){failClosed(error)}
