#!/usr/bin/env node
import path from 'node:path';import {StateStore,root,cdir,argMap,readJson,failClosed,EngineeringOSError} from './lib/core.mjs';import {issueRuntimeExecution} from './lib/execution.mjs';
const a=argMap(),cmd=a._[0]||'status',r=root(),store=new StateStore(r);
try{
 if(cmd==='status'){console.log(JSON.stringify(store.read().workflow,null,2));process.exit(store.read().workflow?0:2)}
 if(cmd==='init'){const result=store.transaction(state=>{const id=String(a.id||state.mission.workflowId||'');const def=readJson(path.join(cdir(r),'workflows',`${id}.json`),null);if(!def||def.schemaVersion!==1||def.classification!=='ENFORCED')throw new EngineeringOSError('POLICY_BLOCKED','Workflow is not executable',{id});const execution=issueRuntimeExecution(r,state,{roleId:'mission-controller',capabilities:['workflow:initialize']});state.workflow={schemaVersion:1,workflowId:id,status:'ACTIVE',executionId:execution.executionId,stages:def.stages.map(x=>({...x,status:'PENDING',evidenceIds:[],completedAt:null})),startedAt:new Date().toISOString(),updatedAt:new Date().toISOString()}});console.log(JSON.stringify(result.state.workflow,null,2));process.exit(0)}
 if(!['complete','fail','block'].includes(cmd))throw new EngineeringOSError('POLICY_BLOCKED','Usage: workflow.mjs init|complete|fail|block|status');
 const result=store.transaction(state=>{const stage=state.workflow?.stages.find(x=>x.id===a.stage);if(!stage)throw new EngineeringOSError('POLICY_BLOCKED','Unknown workflow stage',{stage:a.stage});if(stage.status!=='PENDING'&&stage.status!=='ACTIVE')throw new EngineeringOSError('POLICY_BLOCKED','Invalid stage transition',{status:stage.status});const deps=stage.dependsOn.map(id=>state.workflow.stages.find(x=>x.id===id));if(deps.some(x=>x?.status!=='COMPLETED'))throw new EngineeringOSError('POLICY_BLOCKED','Required dependency not complete',{dependencies:deps.map(x=>({id:x?.id,status:x?.status}))});const execution=issueRuntimeExecution(r,state,{roleId:stage.role,capabilities:[`workflow:${cmd}`]});if(cmd==='complete'){const evidenceIds=String(a.evidence||'').split(',').filter(Boolean);if(stage.id==='verify'&&!evidenceIds.length)throw new EngineeringOSError('POLICY_BLOCKED','Verify stage requires evidence');if(stage.id==='independent-review'&&execution.principalClass!=='host-agent'&&execution.principalClass!=='human')throw new EngineeringOSError('UNSUPPORTED_BY_HOST','Independent review stage requires host-issued reviewer principal');stage.status='COMPLETED';stage.evidenceIds=evidenceIds;stage.completedAt=new Date().toISOString()}else{stage.status=cmd==='fail'?'FAILED':'BLOCKED';state.workflow.status=stage.status;for(const next of state.workflow.stages.filter(x=>x.dependsOn.includes(stage.id)))next.status='BLOCKED'}state.workflow.updatedAt=new Date().toISOString();if(state.workflow.stages.every(x=>!x.required||x.status==='COMPLETED'))state.workflow.status='COMPLETED'});console.log(JSON.stringify(result.state.workflow,null,2));
}catch(error){failClosed(error)}
