// Core I/O for the Lander Records Engineering OS runtime. Dependency-free (Node >= 22 built-ins only).
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

export const OS_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
export const REPO_ROOT = path.resolve(OS_DIR, "..");
export const RUN_DIR = path.join(OS_DIR, "state", ".run");

export class OsError extends Error {
  constructor(code, message, details = {}) { super(message); this.code = code; this.details = details; }
}

export const osPath = (...parts) => path.join(OS_DIR, ...parts);
export const repoPath = (...parts) => path.join(REPO_ROOT, ...parts);
export const rel = (full) => path.relative(REPO_ROOT, full).split(path.sep).join("/");
export const nowIso = () => new Date().toISOString();
export const sha256 = (value) => crypto.createHash("sha256").update(value).digest("hex");

export function readJson(file) { return JSON.parse(fs.readFileSync(file, "utf8")); }

/** ADR-0002: .yml files are JSON documents optionally preceded by '#' comment lines. */
export function readYml(file) {
  const text = fs.readFileSync(file, "utf8");
  const body = text.split("\n").filter((line) => !line.startsWith("#")).join("\n").trim();
  try { return JSON.parse(body); } catch (error) { throw new OsError("YML_NOT_JSON", `${rel(file)} is not JSON-compatible YAML: ${error.message}`); }
}
export function writeYml(file, header, value) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const lines = String(header).split("\n").map((line) => `# ${line}`);
  lines.push("# Format: JSON-compatible YAML (ADR-0002). Written by .claude/runtime.");
  atomicWrite(file, `${lines.join("\n")}\n${JSON.stringify(value, null, 2)}\n`);
}
export function writeJson(file, value) { fs.mkdirSync(path.dirname(file), { recursive: true }); atomicWrite(file, `${JSON.stringify(value, null, 2)}\n`); }
export function atomicWrite(file, text) {
  const tmp = `${file}.${process.pid}.tmp`;
  fs.writeFileSync(tmp, text);
  fs.renameSync(tmp, file);
}

export function walk(dir, filter = () => true) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    if (entry.name === "node_modules" || entry.name === ".git" || entry.name === ".next" || entry.name === ".run") return [];
    const full = path.join(dir, entry.name);
    return entry.isDirectory() ? walk(full, filter) : filter(full) ? [full] : [];
  });
}

export function git(args, { allowFail = false } = {}) {
  const result = spawnSync("git", args, { cwd: REPO_ROOT, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
  if (result.status !== 0 && !allowFail) throw new OsError("GIT_FAILED", `git ${args.join(" ")} failed: ${result.stderr.trim()}`);
  return result.status === 0 ? result.stdout.trim() : "";
}

// OS record directories are bookkeeping about the workspace, not part of it: recording evidence,
// transitioning findings or committing them must not invalidate evidence about the product.
export const RECORD_PATHS = [".claude/state", ".claude/evidence", ".claude/findings", ".claude/reports"];
// Files regenerated by the toolchain itself (next build/dev rewrite next-env.d.ts); not workspace content.
export const GENERATED_PATHS = ["next-env.d.ts"];

/** Content identity of the workspace: index blobs + worktree diff + untracked contents (HEAD-independent). */
export function workspaceFingerprint() {
  const head = git(["rev-parse", "HEAD"], { allowFail: true }) || "NO_HEAD";
  const exclude = [...RECORD_PATHS, ...GENERATED_PATHS].map((p) => `:(exclude)${p}`);
  const index = git(["ls-files", "-s", "--", ".", ...exclude], { allowFail: true });
  const staged = git(["diff", "--cached", "--name-only", "--", ".", ...exclude], { allowFail: true });
  const unstaged = git(["diff", "--binary", "--", ".", ...exclude], { allowFail: true });
  const untracked = git(["ls-files", "--others", "--exclude-standard", "--", ".", ...exclude], { allowFail: true }).split("\n").filter(Boolean).sort();
  const hash = crypto.createHash("sha256").update(index).update("\0").update(unstaged);
  for (const file of untracked) {
    hash.update(`\0${file}\0`);
    try { hash.update(fs.readFileSync(repoPath(file))); } catch { hash.update("UNREADABLE"); }
  }
  return { head, fingerprint: hash.digest("hex"), dirty: Boolean(staged || unstaged || untracked.length) };
}

/** Path from a `git status --porcelain` line (robust to the trimmed first line). */
export const porcelainPath = (line) => line.replace(/^[ MADRCUT?!]{1,2}\s+/, "").replace(/^.* -> /, "");

/**
 * Environment for executed checks: never leak a test-runner context or node/npm option overrides (they can mask
 * failures). npm user/global config files are neutralised and `script-shell` is pinned (a `script-shell` in any
 * npmrc turns every script into a no-op), and `node-options` is emptied. HOME is inherited; PATH is inherited with
 * the running node's directory first. A project .npmrc is refused outright by `npmConfigError`.
 */
export function childEnv(extra = {}) {
  const env = { ...process.env, ...extra };
  for (const name of Object.keys(env)) if (name === "NODE_TEST_CONTEXT" || name === "NODE_OPTIONS" || /^npm_config_/i.test(name)) delete env[name];
  env.npm_config_userconfig = "/dev/null";
  env.npm_config_globalconfig = "/dev/null/npmrc"; // cannot exist (npm rejects loading /dev/null twice)
  env.npm_config_script_shell = "/bin/sh"; // environment config outranks a project .npmrc script-shell
  env.npm_config_node_options = ""; // …and its node-options (npm would export them as NODE_OPTIONS to scripts)
  // Programs a script invokes (node inside `npm run`) resolve next to the running node first.
  env.PATH = [path.dirname(process.execPath), env.PATH].filter(Boolean).join(path.delimiter);
  return env;
}

/** A project .npmrc can change how npm runs scripts; executed npm/npx commands refuse to run while one exists. */
export function npmConfigError(argv) {
  let i = 0;
  if (argv[0] === "env") { i = 1; while (i < argv.length && /^[A-Za-z_][A-Za-z0-9_]*=/.test(argv[i])) i += 1; }
  if (!["npm", "npx"].includes(argv[i])) return null;
  return fs.existsSync(path.join(REPO_ROOT, ".npmrc")) ? "a project .npmrc exists: npm/npx proof and verify commands do not run under project npm configuration" : null;
}

/** argv with node/npm/npx resolved next to the running node binary, not looked up on PATH. */
export function resolveArgv(argv) {
  const out = [...argv];
  let i = 0;
  if (out[0] === "env") { i = 1; while (i < out.length && /^[A-Za-z_][A-Za-z0-9_]*=/.test(out[i])) i += 1; }
  const dir = path.dirname(process.execPath);
  if (out[i] === "node") out[i] = process.execPath;
  else if (["npm", "npx"].includes(out[i]) && fs.existsSync(path.join(dir, out[i]))) out[i] = path.join(dir, out[i]);
  return out;
}

export function args(argv = process.argv.slice(2)) {
  const out = { _: [] };
  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];
    if (token === "--") { out["--"] = argv.slice(index + 1); break; }
    if (token.startsWith("--")) {
      const key = token.slice(2);
      const next = argv[index + 1];
      if (next === undefined || next.startsWith("--")) out[key] = true;
      else { out[key] = next; index += 1; }
    } else out._.push(token);
  }
  return out;
}

export function nextId(dir, prefix) {
  const numbers = fs.existsSync(dir) ? fs.readdirSync(dir).map((name) => name.match(new RegExp(`^${prefix}-(\\d{4})`))?.[1]).filter(Boolean).map(Number) : [];
  return `${prefix}-${String((numbers.length ? Math.max(...numbers) : 0) + 1).padStart(4, "0")}`;
}

/** Directory lock (O_EXCL lock file, stale after 60s) serializing id allocation and chain linking. */
export function withLock(dir, fn) {
  fs.mkdirSync(dir, { recursive: true });
  const lock = path.join(dir, ".lock");
  const deadline = Date.now() + 30_000;
  for (;;) {
    try { fs.closeSync(fs.openSync(lock, "wx")); break; } catch (error) {
      if (error.code !== "EEXIST") throw error;
      try { if (Date.now() - fs.statSync(lock).mtimeMs > 60_000) { fs.rmSync(lock, { force: true }); continue; } } catch { continue; }
      if (Date.now() > deadline) throw new OsError("LOCK_TIMEOUT", `could not lock ${rel(dir)}`);
      Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 25);
    }
  }
  try { return fn(); } finally { fs.rmSync(lock, { force: true }); }
}

/** Serialized record creation: next id + exclusive create, under the directory lock. */
export function createRecord(dir, prefix, build) {
  return withLock(dir, () => {
    const id = nextId(dir, prefix);
    const record = build(id);
    const fd = fs.openSync(path.join(dir, `${id}.json`), "wx");
    try { fs.writeSync(fd, `${JSON.stringify(record, null, 2)}\n`); } finally { fs.closeSync(fd); }
    return record;
  });
}

/** Minimal shell-like split for declared verify commands ("a b 'c d'"). No expansion, no operators. */
export function splitCommand(text) {
  const out = [];
  for (const m of String(text).matchAll(/"([^"]*)"|'([^']*)'|(\S+)/g)) out.push(m[1] ?? m[2] ?? m[3]);
  if (out.some((t) => /^(\||&&|;|>|<|\|\|)$/.test(t))) throw new OsError("USAGE", "verify commands cannot contain shell operators");
  return out;
}

/** Decisions: DEC-NNNN is OPEN until its file says "Status: DECIDED" (or ACCEPTED/SUPERSEDED). */
export function decisionStatus(id) {
  const dir = osPath("decisions");
  const file = fs.existsSync(dir) ? fs.readdirSync(dir).find((n) => n.startsWith(`${id}-`) || n === `${id}.md`) : null;
  if (!file) return "MISSING";
  const status = fs.readFileSync(path.join(dir, file), "utf8").match(/^- Status:\s*([A-Z_]+)/m)?.[1];
  return status || "OPEN";
}

export function run(main) {
  Promise.resolve().then(main).catch((error) => {
    const code = error instanceof OsError ? error.code : "RUNTIME_ERROR";
    console.error(JSON.stringify({ ok: false, code, message: error.message, details: error.details ?? {} }, null, 2));
    process.exit(code === "BLOCKED" ? 77 : 1);
  });
}

/** Reads many `<rev>:<path>` blobs through one `git cat-file --batch` process; missing blobs map to null. */
export function catFiles(specs) {
  const out = new Map();
  if (!specs.length) return out;
  const res = spawnSync("git", ["cat-file", "--batch"], { cwd: REPO_ROOT, input: `${specs.join("\n")}\n`, maxBuffer: 256 * 1024 * 1024 });
  const buf = res.stdout || Buffer.alloc(0);
  let pos = 0;
  for (const spec of specs) {
    const nl = buf.indexOf(10, pos);
    if (nl < 0) break;
    const header = buf.subarray(pos, nl).toString("utf8");
    pos = nl + 1;
    const m = header.match(/^\S+ blob (\d+)$/);
    if (!m) { out.set(spec, null); continue; }
    out.set(spec, buf.subarray(pos, pos + Number(m[1])).toString("utf8"));
    pos += Number(m[1]) + 1;
  }
  return out;
}
