import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {execFileSync,spawnSync} from 'node:child_process';
import {StateStore} from '../lib/store.mjs';
const source=path.resolve(import.meta.dirname,'../../..'),runtime=path.join(source,'.codex','runtime');
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'eos-gov-'));for(const dir of ['contracts','agents','workflows'])fs.mkdirSync(path.join(root,'.codex',dir),{recursive:true});for(const name of fs.readdirSync(path.join(source,'.codex','contracts')))if(name.endsWith('.schema.json'))fs.copyFileSync(path.join(source,'.codex','contracts',name),path.join(root,'.codex','contracts',name));fs.copyFileSync(path.join(source,'.codex','agents','registry.json'),path.join(root,'.codex','agents','registry.json'));fs.copyFileSync(path.join(source,'.codex','workflows','brownfield-change.json'),path.join(root,'.codex','workflows','brownfield-change.json'));fs.writeFileSync(path.join(root,'.codex','state-location.json'),JSON.stringify({schemaVersion:1,authoritativeState:'.local/state.json'}));execFileSync('git',['init','-b','dev'],{cwd:root,stdio:'ignore'});for(const [k,v] of [['user.email','eos@test.invalid'],['user.name','EOS Test'],['core.autocrlf','false']])execFileSync('git',['config',k,v],{cwd:root});fs.writeFileSync(path.join(root,'seed.txt'),'seed');fs.writeFileSync(path.join(root,'.gitignore'),'.local/\n');execFileSync('git',['add','.'],{cwd:root,stdio:'ignore'});execFileSync('git',['commit','-m','fixture'],{cwd:root,stdio:'ignore'});new StateStore(root).initialize();return root}
const run=(root,file,args=[])=>spawnSync(process.execPath,[path.join(runtime,file),...args],{cwd:root,env:{...process.env,CODEX_PROJECT_DIR:root},encoding:'utf8'}),out=p=>`${p.stdout||''}${p.stderr||''}`,clean=root=>fs.rmSync(root,{recursive:true,force:true});
function mission(root){new StateStore(root).transaction(s=>{s.mission={id:'M1',title:'test',status:'IMPLEMENTATION_COMPLETE',scope:'bounded',workflowId:null,startedAt:new Date().toISOString(),updatedAt:new Date().toISOString(),workspaceFingerprintAtStart:'0'.repeat(64),rootExecutionId:null};s.requirements=[{id:'R1',text:'r',criteria:['C1']}];s.criteria=[{id:'C1',requirementId:'R1',text:'c',mandatory:true,evidenceKinds:['test']}]})}
test('33 empty mission is blocked',()=>{const r=fixture();try{const p=run(r,'completion-gate.mjs');assert.notEqual(p.status,0);assert.match(p.stdout,/mission-not-ready|requirements-empty/)}finally{clean(r)}});
test('34 zero criteria is blocked',()=>{const r=fixture();try{new StateStore(r).transaction(s=>{s.mission={...s.mission,id:'M',status:'IMPLEMENTATION_COMPLETE'};s.requirements=[{id:'R',text:'r',criteria:[]}]});assert.match(run(r,'completion-gate.mjs').stdout,/criteria-empty/)}finally{clean(r)}});
test('35 claimed PASS without execution is rejected',()=>{const r=fixture();try{mission(r);const p=run(r,'evidence.mjs',['run','--criterion','C1','--result','PASS','--',process.execPath,'-e','process.exit(0)']);assert.notEqual(p.status,0);assert.match(out(p),/POLICY_BLOCKED/)}finally{clean(r)}});
test('36 nonzero command exit derives FAIL',()=>{const r=fixture();try{mission(r);const p=run(r,'evidence.mjs',['run','--criterion','C1','--',process.execPath,'-e','process.exit(9)']);assert.notEqual(p.status,0);const e=new StateStore(r).read().evidence.at(-1);assert.equal(e.result,'FAIL');assert.equal(e.exitCode,9)}finally{clean(r)}});
test('37 fabricated producer is rejected',()=>{const r=fixture();try{mission(r);const p=run(r,'evidence.mjs',['run','--criterion','C1','--producer','qa-engineer','--',process.execPath,'-e','process.exit(0)']);assert.notEqual(p.status,0);assert.match(out(p),/POLICY_BLOCKED/)}finally{clean(r)}});
test('38 forbidden static evidence is rejected',()=>{const r=fixture();try{mission(r);const p=run(r,'evidence.mjs',['run','--criterion','C1','--static','--',process.execPath,'-e','process.exit(0)']);assert.notEqual(p.status,0);assert.match(out(p),/POLICY_BLOCKED/)}finally{clean(r)}});
test('39 direct CRITICAL closure is rejected',()=>{const r=fixture();try{run(r,'finding.mjs',['record','--id','F1','--severity','CRITICAL','--summary','critical']);const p=run(r,'finding.mjs',['resolve','--id','F1']);assert.notEqual(p.status,0);assert.equal(new StateStore(r).read().findings[0].status,'OPEN')}finally{clean(r)}});
test('40 local self-verification of CRITICAL is unsupported',()=>{const r=fixture();try{mission(r);assert.equal(run(r,'finding.mjs',['record','--id','F1','--severity','CRITICAL','--summary','critical']).status,0);assert.equal(run(r,'finding.mjs',['start','--id','F1']).status,0);assert.equal(run(r,'evidence.mjs',['run','--criterion','C1','--',process.execPath,'-e','process.exit(0)']).status,0);const ev=new StateStore(r).read().evidence.at(-1),marked=run(r,'finding.mjs',['mark-fixed','--id','F1','--resolution','fix','--evidence',ev.id]);assert.equal(marked.status,0,out(marked));const p=run(r,'finding.mjs',['verify','--id','F1','--evidence',ev.id]);assert.notEqual(p.status,0);assert.match(out(p),/UNSUPPORTED_BY_HOST/)}finally{clean(r)}});
test('41 reviewer name cannot grant independence',()=>{const r=fixture();try{const p=run(r,'review.mjs',['record-advisory','--reviewer','security-reviewer','--result','PASS']);assert.notEqual(p.status,0);assert.equal(new StateStore(r).read().reviews.length,0)}finally{clean(r)}});
test('42 self-asserted A5 is rejected',()=>{const r=fixture();try{const p=run(r,'policy-gate.mjs',['--current','A5','--required','A5','--action','production']);assert.notEqual(p.status,0);assert.match(out(p),/POLICY_BLOCKED/)}finally{clean(r)}});
test('43 graph rejects fake role and writer without ownership',()=>{const r=fixture();try{const json=JSON.stringify({nodes:[{id:'n',role:'fake-role',mode:'write',ownership:[],dependsOn:[],retryBudget:0,timeoutMs:10,executionId:'fake'}]});const p=run(r,'execution-graph.mjs',['save','--json',json]);assert.notEqual(p.status,0);assert.match(p.stdout,/unknown-role/);assert.match(p.stdout,/writer-without-ownership/)}finally{clean(r)}});
test('44 graph rejects mode mismatch',()=>{const r=fixture();try{const json=JSON.stringify({nodes:[{id:'n',role:'mission-controller',mode:'write',ownership:['src'],dependsOn:[],retryBudget:0,timeoutMs:10,executionId:'fake'}]});const p=run(r,'execution-graph.mjs',['save','--json',json]);assert.notEqual(p.status,0);assert.match(p.stdout,/mode-mismatch/)}finally{clean(r)}});
test('45 workflow cannot skip required dependency',()=>{const r=fixture();try{new StateStore(r).transaction(s=>{s.mission={...s.mission,id:'M',status:'ACTIVE',workflowId:'brownfield-change'}});assert.equal(run(r,'workflow.mjs',['init']).status,0);const p=run(r,'workflow.mjs',['complete','--stage','impact']);assert.notEqual(p.status,0);assert.match(out(p),/Required dependency not complete/)}finally{clean(r)}});
