"use client";

import Image from "next/image";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { AdminIcon, type IconName } from "../../components/AdminIcon";
import styles from "./NewsManager.module.css";

export type PostSummary = { id: string; title: string; slug: string; excerpt: string; status: "draft" | "published" | "archived" | "unpublished"; category: string; authorName: string; publishedAt: string; coverImage: string; featuredOnHome: boolean; tags: string[]; isPubliclyVisible: boolean; updatedAt: string };
type Filters = { category?: string; q?: string; status?: string; tag?: string };

function StatusBadge({ status }: { status: PostSummary["status"] }) {
  const label = status === "published" ? "Publicado" : status === "archived" ? "Arquivado" : status === "unpublished" ? "Não publicada" : "Rascunho";
  return <span className={status === "published" ? "adminBadge live" : status === "archived" ? "adminBadge archived" : "adminBadge draft"}><i aria-hidden="true" />{label}</span>;
}

export default function PostManager({ availableCategories, availableTags, canEdit = true, deleted, initialFilters = {}, metrics: metricCounts, posts, preview = false }: { availableCategories?: string[]; availableTags?: string[]; canEdit?: boolean; deleted?: boolean; initialFilters?: Filters; metrics?: { archived: number; drafts: number; published: number; total: number }; posts: PostSummary[]; preview?: boolean }) {
  const router = useRouter(); const pathname = usePathname();
  const [query, setQuery] = useState(initialFilters.q || ""); const [status, setStatus] = useState(initialFilters.status || "all"); const [category, setCategory] = useState(initialFilters.category || "all"); const [tag, setTag] = useState(initialFilters.tag || "all");
  const categories = useMemo(() => availableCategories || Array.from(new Set(posts.map((post) => post.category))).sort((a, b) => a.localeCompare(b, "pt-BR")), [availableCategories, posts]);
  const tags = useMemo(() => availableTags || Array.from(new Set(posts.flatMap((post) => post.tags))).sort((a, b) => a.localeCompare(b, "pt-BR")), [availableTags, posts]);
  useEffect(() => { if (preview) return; const params = new URLSearchParams(); if (query.trim()) params.set("q", query.trim()); if (status !== "all") params.set("status", status); if (category !== "all") params.set("category", category); if (tag !== "all") params.set("tag", tag); const timer = window.setTimeout(() => router.replace(`${pathname}${params.size ? `?${params}` : ""}`, { scroll: false }), 180); return () => window.clearTimeout(timer); }, [category, pathname, preview, query, router, status, tag]);
  const filtered = useMemo(() => { if (!preview) return posts; const needle = query.trim().toLocaleLowerCase("pt-BR"); return posts.filter((post) => (!needle || [post.title, post.slug, post.excerpt, post.authorName, post.category, ...post.tags].join(" ").toLocaleLowerCase("pt-BR").includes(needle)) && (status === "all" || post.status === status) && (category === "all" || post.category === category) && (tag === "all" || post.tags.includes(tag))); }, [category, posts, preview, query, status, tag]);
  const hasFilters = Boolean(query.trim() || status !== "all" || category !== "all" || tag !== "all"); const clearFilters = () => { setQuery(""); setStatus("all"); setCategory("all"); setTag("all"); };
  const counts = metricCounts || { total: posts.length, published: posts.filter((post) => post.isPubliclyVisible).length, drafts: posts.filter((post) => post.status === "draft").length, archived: posts.filter((post) => post.status === "archived").length };
  const metrics: Array<[IconName, string, number, string]> = [["posts", "Total de notícias", counts.total, "Cadastradas"], ["pages", "Publicadas", counts.published, "Visíveis no site"], ["calendar", "Rascunhos", counts.drafts, "Não publicadas"], ["audit", "Arquivadas", counts.archived, "Fora do site"]];
  return <div className={styles.manager} data-testid="news-manager">
    {preview ? <div className="adminPreviewNotice">BACKEND_ENVIRONMENT_DEFERRED · dados editoriais isolados e sem persistência.</div> : null}
    <header className={styles.header}><div><p>Notícias / Visão geral</p><h1>Notícias</h1><span>Gerencie as notícias do site. Crie, edite e publique conteúdo editorial.</span></div>{canEdit && !preview ? <Link className="adminButton primary" href="/admin/posts/new">＋ Nova notícia</Link> : preview ? <button className="adminButton primary" disabled type="button">＋ Nova notícia</button> : null}</header>
    {deleted ? <div className={styles.success}>Notícia excluída com sucesso.</div> : null}
    <section aria-label="Resumo editorial das notícias" className={styles.metrics}>{metrics.map(([icon, label, value, detail]) => <article data-testid="news-metric-card" key={label}><span className={styles.metricIcon}><AdminIcon name={icon} /></span><div><small>{label}</small><strong>{value}</strong><p>{detail}</p></div></article>)}</section>
    <section className={styles.catalog}><div className={styles.toolbar} role="search"><label className={styles.search}><span className="srOnly">Buscar notícias</span><AdminIcon name="search" size={17} /><input onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por título, resumo ou autor..." type="search" value={query} /></label><label><span>Status</span><select onChange={(event) => setStatus(event.target.value)} value={status}><option value="all">Todos</option><option value="published">Publicadas</option><option value="draft">Rascunhos</option><option value="archived">Arquivadas</option></select></label><label><span>Categoria</span><select onChange={(event) => setCategory(event.target.value)} value={category}><option value="all">Todas</option>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label><span>Tag</span><select onChange={(event) => setTag(event.target.value)} value={tag}><option value="all">Todas</option>{tags.map((item) => <option key={item}>{item}</option>)}</select></label>{hasFilters && filtered.length ? <button className="adminButton" onClick={clearFilters} type="button">Limpar filtros</button> : null}</div>
      {filtered.length ? <div aria-label="Notícias cadastradas" role="table"><div className={styles.tableHeader} role="row">{["Notícia", "Categoria", "Status", "Publicada em", "Atualizada em", "Ações"].map((label) => <span key={label} role="columnheader">{label}</span>)}</div><div className={styles.rows} role="rowgroup">{filtered.map((post) => <div className={styles.row} data-testid="news-row" key={post.id} role="row"><div aria-label={`Notícia: ${post.title}`} className={styles.identity} role="cell">{post.coverImage ? <Image alt={`Capa de ${post.title}`} height={72} src={post.coverImage} unoptimized width={72} /> : <span className={styles.coverFallback} aria-hidden="true"><AdminIcon name="posts" /></span>}<span><strong>{post.title}</strong><p>{post.excerpt || "Sem resumo editorial."}</p><small>{post.authorName === "Não informado" ? "Autor não informado" : `Por ${post.authorName}`}</small></span></div><div aria-label={`Categoria: ${post.category}`} className={styles.category} role="cell"><span>{post.category}</span></div><div role="cell"><StatusBadge status={post.status} /></div><div className={styles.date} role="cell"><strong>{post.publishedAt || "—"}</strong><small>{post.isPubliclyVisible ? "Publicada" : "Não publicada"}</small></div><time className={styles.date} role="cell">{post.updatedAt}</time><div aria-label={`Ações de ${post.title}`} className={styles.actions} role="cell">{canEdit && !preview ? <><Link aria-label={`Editar ${post.title}`} href={`/admin/posts/${post.id}`}><AdminIcon name="pages" size={16} /></Link><Link aria-label={`Consultar ${post.title} no CMS`} href={`/admin/posts/${post.id}/view`}><AdminIcon name="posts" size={16} /></Link></> : null}{preview ? <button aria-label={`Editar ${post.title}`} disabled type="button"><AdminIcon name="pages" size={16} /></button> : null}{post.isPubliclyVisible && !preview ? <Link aria-label={`Visualizar notícia pública ${post.title} (abre em nova aba)`} href={`/noticias/${post.slug}`} target="_blank"><AdminIcon name="external" size={16} /></Link> : preview ? <button aria-label={`Notícia pública ${post.title} indisponível no preview`} disabled type="button"><AdminIcon name="external" size={16} /></button> : null}</div></div>)}</div><div className={styles.resultCount}>Mostrando {filtered.length} de {counts.total} notícias</div></div> : <div className={styles.empty} data-testid="news-empty"><strong>{posts.length ? "Nenhuma notícia encontrada para os filtros selecionados." : "Nenhuma notícia cadastrada."}</strong>{hasFilters ? <button className="adminButton" onClick={clearFilters} type="button">Limpar filtros</button> : canEdit && !preview ? <Link className="adminButton primary" href="/admin/posts/new">Criar primeira notícia</Link> : null}</div>}
    </section>
    <section className={styles.shortcuts} aria-label="Atalhos editoriais"><article><AdminIcon name="pages" /><div><h2>Rascunhos</h2><p>Continue editando notícias ainda não publicadas.</p>{preview ? null : <Link className="adminButton" href="/admin/posts?status=draft">Ver rascunhos</Link>}</div></article><article><AdminIcon name="navigation" /><div><h2>Categorias</h2><p>Gerencie a classificação editorial das notícias.</p>{preview ? null : <Link className="adminButton" href="/admin/post-categories">Gerenciar categorias</Link>}</div></article><article><AdminIcon name="tags" /><div><h2>Tags</h2><p>Organize o conteúdo com as tags existentes.</p>{preview ? null : <Link className="adminButton" href="/admin/tags">Gerenciar tags</Link>}</div></article></section>
    <div className={styles.homeNotice}><span aria-hidden="true">i</span>As notícias publicadas e selecionadas para destaque alimentam a seção Últimas Notícias da Home.</div>
  </div>;
}
